name: logger_console
description: A logger project
version: 0.1.1
homepage: https://github.com/Nghi-NV/logger-console
maintainer: nghinv (@Nghi-NV)

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.3
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
